# Forest Cover - Neural Network

Import libraries

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from keras.models import Model
from keras.models import Sequential
from keras.layers import Input, Dense, Dropout, Activation
from keras.optimizers import RMSprop, Adam, Nadam, Adamax
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

/Users/jamster/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/jamster/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/jamster/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/jamster/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

## Import Data

In [3]:
data = pd.read_csv('train.csv')

In [4]:
data.head(5)

   Id  Elevation  Aspect  ...  Soil_Type39  Soil_Type40  Cover_Type
0   1       2596      51  ...            0            0           5
1   2       2590      56  ...            0            0           5
2   3       2804     139  ...            0            0           2
3   4       2785     155  ...            0            0           2
4   5       2595      45  ...            0            0           5

[5 rows x 56 columns]

In [5]:
data = data.drop('Id', axis=1)
data['Cover_Type'] = data['Cover_Type'].astype('category')

In [6]:
data.head(5)

   Elevation  Aspect  Slope  ...  Soil_Type39  Soil_Type40  Cover_Type
0       2596      51      3  ...            0            0           5
1       2590      56      2  ...            0            0           5
2       2804     139      9  ...            0            0           2
3       2785     155     18  ...            0            0           2
4       2595      45      2  ...            0            0           5

[5 rows x 55 columns]

In [7]:
data.dtypes

Elevation                                int64
Aspect                                   int64
Slope                                    int64
Horizontal_Distance_To_Hydrology         int64
Vertical_Distance_To_Hydrology           int64
Horizontal_Distance_To_Roadways          int64
Hillshade_9am                            int64
Hillshade_Noon                           int64
Hillshade_3pm                            int64
Horizontal_Distance_To_Fire_Points       int64
Wilderness_Area1                         int64
Wilderness_Area2                         int64
Wilderness_Area3                         int64
Wilderness_Area4                         int64
Soil_Type1                               int64
Soil_Type2                               int64
Soil_Type3                               int64
Soil_Type4                               int64
Soil_Type5                               int64
Soil_Type6                               int64
Soil_Type7                               int64
Soil_Type8                               int64
Soil_Type9                               int64
Soil_Type10                              int64
Soil_Type11                              int64
Soil_Type12                              int64
Soil_Type13                              int64
Soil_Type14                              int64
Soil_Type15                              int64
Soil_Type16                              int64
Soil_Type17                              int64
Soil_Type18                              int64
Soil_Type19                              int64
Soil_Type20                              int64
Soil_Type21                              int64
Soil_Type22                              int64
Soil_Type23                              int64
Soil_Type24                              int64
Soil_Type25                              int64
Soil_Type26                              int64
Soil_Type27                              int64
Soil_Type28                              int64
Soil_Type29                              int64
Soil_Type30                              int64
Soil_Type31                              int64
Soil_Type32                              int64
Soil_Type33                              int64
Soil_Type34                              int64
Soil_Type35                              int64
Soil_Type36                              int64
Soil_Type37                              int64
Soil_Type38                              int64
Soil_Type39                              int64
Soil_Type40                              int64
Cover_Type                            category
dtype: object

In [8]:
features = data.drop('Cover_Type', axis=1)
features.head(5)

   Elevation  Aspect  Slope  ...  Soil_Type38  Soil_Type39  Soil_Type40
0       2596      51      3  ...            0            0            0
1       2590      56      2  ...            0            0            0
2       2804     139      9  ...            0            0            0
3       2785     155     18  ...            0            0            0
4       2595      45      2  ...            0            0            0

[5 rows x 54 columns]

In [9]:
types = data['Cover_Type']
types.head(5)

0    5
1    5
2    2
3    2
4    5
Name: Cover_Type, dtype: category
Categories (7, int64): [1, 2, 3, 4, 5, 6, 7]

Convert to categories

In [15]:
from keras.utils import to_categorical

typesCats = to_categorical(types)
typesCats

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

### Train/Test Split

In [19]:
train_features, test_features, train_types, test_types = train_test_split(features, types, test_size = 0.15, random_state = 42)

In [22]:
train_features, test_features, train_typesCats, test_typesCats = train_test_split(features, typesCats, test_size = 0.15, random_state = 42)

## Neural Network

In [38]:
def NNmodel():
    myInputs = Input(shape=(54,))

    x = Dense(54)(myInputs)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.30)(x)
    
    x = Dense(51)(myInputs)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.28)(x)
    
    x = Dense(12)(myInputs)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.07)(x)
    
    x = Dense(8)(x)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.05)(x)
    
    myPredicts = Dense(8)(x)
    myModel = Model(inputs=myInputs, outputs=myPredicts)
    
    return myModel

In [43]:
def NNmodel():
    myInputs = Input(shape=(54,))

    x = Dense(108)(myInputs)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.26)(x)
    
    x = Dense(108)(x)
    x = Activation('relu')(x)
#     x = Dropout(0.26)(x)
    
    x = Dense(108)(x)
    x = Activation('softmax')(x)
#     x = Dropout(0.26)(x)
    
#     x = Dense(108)(x)
#     x = Activation('relu')(x)
#     x = Dropout(0.26)(x)
    

    x = Dense(162)(x)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.39)(x)
    
    x = Dense(162)(x)
    x = Activation('relu')(x)
#     x = Dropout(0.39)(x)
    
    x = Dense(162)(x)
    x = Activation('softmax')(x)
#     x = Dropout(0.39)(x)
    
#     x = Dense(162)(x)
#     x = Activation('sigmoid')(x)
#     x = Dropout(0.39)(x)
    
    
    x = Dense(108)(x)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.26)(x)
    
    x = Dense(108)(x)
    x = Activation('relu')(x)
#     x = Dropout(0.26)(x)
    
    x = Dense(108)(x)
    x = Activation('softmax')(x)
#     x = Dropout(0.26)(x)
    
#     x = Dense(108)(x)
#     x = Activation('relu')(x)
#     x = Dropout(0.26)(x)
    

    x = Dense(54)(x)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.13)(x)
    
    x = Dense(54)(x)
    x = Activation('relu')(x)
#     x = Dropout(0.13)(x)
    
    x = Dense(54)(x)
    x = Activation('softmax')(x)
#     x = Dropout(0.13)(x)
    
#     x = Dense(54)(myInputs)
#     x = Activation('sigmoid')(x)
#     x = Dropout(0.13)(x)
    
    
    x = Dense(108)(x)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.26)(x)
    
    x = Dense(108)(x)
    x = Activation('relu')(x)
#     x = Dropout(0.26)(x)
    
    x = Dense(108)(x)
    x = Activation('softmax')(x)
#     x = Dropout(0.26)(x)
    
#     x = Dense(108)(x)
#     x = Activation('relu')(x)
#     x = Dropout(0.26)(x)
    
    
    x = Dense(102)(x)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.24)(x)
    
    x = Dense(102)(x)
    x = Activation('relu')(x)
#     x = Dropout(0.24)(x)
    
    x = Dense(102)(x)
    x = Activation('softmax')(x)
#     x = Dropout(0.24)(x)
    
#     x = Dense(102)(x)
#     x = Activation('relu')(x)
#     x = Dropout(0.24)(x)
    
    
    x = Dense(51)(x)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.12)(x)
    
    x = Dense(51)(x)
    x = Activation('relu')(x)
#     x = Dropout(0.12)(x)
    
    x = Dense(51)(x)
    x = Activation('softmax')(x)
#     x = Dropout(0.12)(x)
    
#     x = Dense(51)(x)
#     x = Activation('sigmoid')(x)
#     x = Dropout(0.12)(x)
    
    
    x = Dense(24)(x)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.06)(x)
    
    x = Dense(24)(x)
    x = Activation('relu')(x)
#     x = Dropout(0.06)(x)
    
    x = Dense(24)(x)
    x = Activation('softmax')(x)
#     x = Dropout(0.06)(x)
    
#     x = Dense(24)(x)
#     x = Activation('sigmoid')(x)
#     x = Dropout(0.06)(x)
    
    
    x = Dense(12)(x)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.03)(x)
    
    x = Dense(12)(x)
    x = Activation('relu')(x)
#     x = Dropout(0.03)(x)
    
    x = Dense(12)(x)
    x = Activation('softmax')(x)
#     x = Dropout(0.03)(x)
    
#     x = Dense(12)(x)
#     x = Activation('sigmoid')(x)
#     x = Dropout(0.03)(x)
    
    
#     x = Dense(10)(x)
#     x = Activation('sigmoid')(x)
#     x = Dropout(0.03)(x)
    
    
    x = Dense(8)(x)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.02)(x)
    
    x = Dense(8)(x)
    x = Activation('relu')(x)
#     x = Dropout(0.02)(x)
    
    x = Dense(8)(x)
    x = Activation('softmax')(x)
#     x = Dropout(0.02)(x)
    
#     x = Dense(8)(x)
#     x = Activation('sigmoid')(x)
#     x = Dropout(0.02)(x)


    x = Dense(8)(x)
    x = Activation('sigmoid')(x)
#     x = Dropout(0.02)(x)
    
    myPredicts = Dense(8)(x)
    myModel = Model(inputs=myInputs, outputs=myPredicts)
    
    return myModel

In [44]:
model = NNmodel()
# myRMS = RMSprop(lr=0.0005, rho=0.9, epsilon=None, decay=0.0)
# model.compile(optimizer=myRMS, loss='mse', metrics=['mse'])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc', 'accuracy'])

scaler1 = StandardScaler()
scaler1 = scaler1.fit(train_features)
xScaled0 = scaler1.transform(train_features)

scaler2 = MinMaxScaler(feature_range=(0,1))
scaler2 = scaler2.fit(xScaled0)
xScaled = scaler2.transform(xScaled0)

# model.fit(xScaled, train_types, epochs=25, verbose=0)
model.fit(xScaled, train_typesCats, epochs=25)

xTestScale0 = scaler1.transform(test_features)
xTestScale = scaler2.transform(xTestScale0)

y_pred = model.predict(xTestScale)

/Users/jamster/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/jamster/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.

Epoch 1/25
12852/12852 [==============================] - 21s 2ms/step - loss: 12.1455 - acc: 0.1428 - acc_1: 0.1428
Epoch 2/25
12852/12852 [==============================] - 10s 794us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 3/25
12852/12852 [==============================] - 9s 707us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 4/25
12852/12852 [==============================] - 9s 720us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.14280s - loss: 13.8110 - acc: 0.1431 - acc_1: 0.
Epoch 5/25
12852/12852 [==============================] - 8s 649us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 6/25
12852/12852 [==============================] - 9s 718us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 7/25
12852/12852 [==============================] - 9s 734us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 8/25
12852/12852 [==============================] - 10s 744us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 9/25
12852/12852 [==============================] - 9s 737us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 10/25
12852/12852 [==============================] - 9s 683us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 11/25
12852/12852 [==============================] - 9s 677us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 12/25
12852/12852 [==============================] - 9s 688us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 13/25
12852/12852 [==============================] - 9s 704us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 14/25
12852/12852 [==============================] - 9s 723us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 15/25
12852/12852 [==============================] - 10s 745us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 16/25
12852/12852 [==============================] - 8s 646us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 17/25
12852/12852 [==============================] - 9s 695us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 18/25
12852/12852 [==============================] - 9s 688us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 19/25
12852/12852 [==============================] - 9s 671us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 20/25
12852/12852 [==============================] - 8s 660us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 21/25
12852/12852 [==============================] - 8s 624us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 22/25
12852/12852 [==============================] - 9s 691us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 23/25
12852/12852 [==============================] - 9s 678us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 24/25
12852/12852 [==============================] - 10s 815us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428
Epoch 25/25
12852/12852 [==============================] - 11s 877us/step - loss: 13.8168 - acc: 0.1428 - acc_1: 0.1428

/Users/jamster/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.

In [41]:
model = NNmodel()
# myRMS = RMSprop(lr=0.0005, rho=0.9, epsilon=None, decay=0.0)
# model.compile(optimizer=myRMS, loss='mse', metrics=['mse'])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc', 'accuracy'])

scaler1 = StandardScaler()
scaler1 = scaler1.fit(train_features)
xScaled0 = scaler1.transform(train_features)

scaler2 = MinMaxScaler(feature_range=(0,1))
scaler2 = scaler2.fit(xScaled0)
xScaled = scaler2.transform(xScaled0)

# model.fit(xScaled, train_types, epochs=25, verbose=0)
model.fit(train_features, train_typesCats, epochs=25)

xTestScale0 = scaler1.transform(test_features)
xTestScale = scaler2.transform(xTestScale0)

y_pred = model.predict(xTestScale)

/Users/jamster/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/jamster/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.

Epoch 1/25
12852/12852 [==============================] - 5s 386us/step - loss: 7.8151 - acc: 0.1400 - acc_1: 0.1400
Epoch 2/25
12852/12852 [==============================] - 1s 97us/step - loss: 7.7719 - acc: 0.1539 - acc_1: 0.1539
Epoch 3/25
12852/12852 [==============================] - 1s 102us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 4/25
12852/12852 [==============================] - 1s 113us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 5/25
12852/12852 [==============================] - 2s 121us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 6/25
12852/12852 [==============================] - 1s 87us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 7/25
12852/12852 [==============================] - 1s 101us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 8/25
12852/12852 [==============================] - 1s 85us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 9/25
12852/12852 [==============================] - 1s 99us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 10/25
12852/12852 [==============================] - 1s 85us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 11/25
12852/12852 [==============================] - 1s 96us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 12/25
12852/12852 [==============================] - 1s 116us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 13/25
12852/12852 [==============================] - 1s 100us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 14/25
12852/12852 [==============================] - 1s 103us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 15/25
12852/12852 [==============================] - 1s 99us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 16/25
12852/12852 [==============================] - 1s 86us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 17/25
12852/12852 [==============================] - 1s 107us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 18/25
12852/12852 [==============================] - 2s 124us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 19/25
12852/12852 [==============================] - 1s 112us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 20/25
12852/12852 [==============================] - 2s 120us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 21/25
12852/12852 [==============================] - 1s 110us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 22/25
12852/12852 [==============================] - 1s 94us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 23/25
12852/12852 [==============================] - 1s 108us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 24/25
12852/12852 [==============================] - 1s 104us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539
Epoch 25/25
12852/12852 [==============================] - 1s 92us/step - loss: 7.7154 - acc: 0.1539 - acc_1: 0.1539

/Users/jamster/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.

In [43]:
model = Sequential()

model.add(Dense(54,
				input_dim=54,
				kernel_initializer='uniform',
				activation='relu'))
model.add(Dropout(0.125))

model.add(Dense(108,
				kernel_initializer='uniform',
				activation='relu'))
model.add(Dropout(0.25))

model.add(Dense(162,
				kernel_initializer='uniform',
				activation='relu'))
model.add(Dropout(0.375))

model.add(Dense(108,
				kernel_initializer='uniform',
				activation='sigmoid'))
model.add(Dropout(0.25))

In [44]:
types.max

<bound method Series.max of 0        5
1        5
2        2
3        2
4        5
5        2
6        5
7        5
8        5
9        5
10       5
11       2
12       2
13       5
14       5
15       5
16       5
17       5
18       5
19       5
20       5
21       2
22       5
23       5
24       5
25       5
26       5
27       2
28       2
29       5
        ..
15090    3
15091    3
15092    3
15093    6
15094    6
15095    6
15096    6
15097    3
15098    3
15099    6
15100    3
15101    6
15102    3
15103    6
15104    3
15105    6
15106    3
15107    3
15108    3
15109    6
15110    6
15111    6
15112    6
15113    3
15114    3
15115    3
15116    3
15117    3
15118    3
15119    3
Name: Cover_Type, Length: 15120, dtype: category
Categories (7, int64): [1, 2, 3, 4, 5, 6, 7]>